#!/usr/bin/env node
// Compose little-coder's system prompt from modular layers.
//
//   prompts/base.md                  identity-agnostic core (autonomy, invariants)
//   prompts/tools.md                 tool-emission rules (anti "helper persona")
//   prompts/providers/<provider>.md  persona overlay, one per backend
//   prompts/modes/reanchor.md        post-compaction re-anchor (not part of the
//                                    main assembly; injected separately)
//
// Usage:
//   node scripts/compose-prompt.mjs                     # default provider -> AGENTS.md
//   node scripts/compose-prompt.mjs m365                # provider overlay -> stdout
//   node scripts/compose-prompt.mjs m365 --write        # provider overlay -> AGENTS.md
//   node scripts/compose-prompt.mjs --list              # known providers
//
// AGENTS.md is generated: bin/little-coder.mjs passes it whole via --system-prompt.
// Edit the layer files, never AGENTS.md itself.
// Providers without a dedicated overlay fall back to providers/default.md.

import { readFileSync, writeFileSync, existsSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

// Sections of the legacy AGENTS.md that are still maintained there
// (single source of truth) and carried into every composed prompt.
const PRESERVED_SECTIONS = [
  "Available Tools",
  "Approaching complex tasks",
  "Handling ambiguity",
  "Workspace discovery",
  "Per-turn context augmentation",
  "Guidelines",
];

const pkgRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const promptsDir = join(pkgRoot, "prompts");
const agentsMd = join(pkgRoot, "AGENTS.md");

const GENERATED_TAG = "<!-- GENERATED by scripts/compose-prompt.mjs — edit prompts/* layers, not this file -->";

const availableProviders = readdirSafe(join(promptsDir, "providers"))
  .filter((f) => f.endsWith(".md"))
  .map((f) => f.replace(/\.md$/, ""));

function readdirSafe(dir) {
  try {
    return readdirSync(dir);
  } catch {
    return [];
  }
}

const args = process.argv.slice(2);
const list = args.includes("--list");
const write = args.includes("--write");
const providerArg = args.find((a) => !a.startsWith("--")) ?? "default";

if (list) {
  console.log(availableProviders.join("\n"));
  process.exit(0);
}

if (!availableProviders.includes(providerArg)) {
  process.stderr.write(
    `unknown provider "${providerArg}". Known: ${availableProviders.join(", ")}\n` +
      `(falling back to "default")\n`,
  );
}

const provider = availableProviders.includes(providerArg) ? providerArg : "default";

// Read the legacy AGENTS.md's remaining maintained sections (tool inventory,
// task guidelines, etc.) so they stay in one place until they move to layers.
const legacy = existsSync(agentsMd) ? readFileSync(agentsMd, "utf8") : "";
const preserved = [];
for (const name of PRESERVED_SECTIONS) {
  const re = new RegExp(`^# (?:${name})[\\s\\S]*?(?=^# |$)`, "m");
  const m = legacy.match(re);
  if (m) preserved.push(m[0].trim());
}

const layers = [
  join(promptsDir, "base.md"),
  join(promptsDir, "tools.md"),
  join(promptsDir, "providers", `${provider}.md`),
];

const parts = [GENERATED_TAG];
for (const layer of layers) {
  if (!existsSync(layer)) {
    process.stderr.write(`missing prompt layer: ${layer}\n`);
    process.exit(1);
  }
  parts.push(readFileSync(layer, "utf8").trim());
}
if (preserved.length) parts.push(...preserved);

const out = parts.join("\n\n") + "\n";

if (write) {
  writeFileSync(agentsMd, out);
  process.stderr.write(`composed ${provider} prompt -> AGENTS.md (${out.length} bytes)\n`);
} else if (providerArg === "default" && !process.env.LC_COMPOSE_STDOUT) {
  // bare invocation with no provider arg keeps legacy behavior: regenerate AGENTS.md
  writeFileSync(agentsMd, out);
  process.stderr.write(`composed ${provider} prompt -> AGENTS.md (${out.length} bytes)\n`);
} else {
  process.stdout.write(out);
}
